#!/bin/bash

if ! [[ -z "$1" ]]; then
  count=$(($1))
  while [  $count -gt 0 ]; do
  qdbus org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous >/dev/null
  let count=count-1
  done
else
  qdbus org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous >/dev/null
  exit 0
fi
